//create 404  error when bad request is sent
export const customError = (req, res, next) =>{
    const error = new Error('Not Found');
    error.status = 404;
    next(error);
}

//send back whatever error is generated by the server
export const serverError = (error, req, res, next) =>{
    res.status(error.status || 500).json({
        error: {
            message: error.message
        }
    });
}